{
 "title": "Cloud Monitoring & Alerting Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Service Health",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"sample-node-service\"}"
    }
   ]
  },
  {
   "title": "Targets UP/DOWN",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 0, "w": 16, "h": 5 },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 5, "w": 12, "h": 7 },
   "targets": [
    {
     "expr": "sum(rate(app_http_requests_total[1m])) by (route, status_code)"
    }
   ]
  },
  {
   "title": "p95 Latency",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 5, "w": 12, "h": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_http_request_duration_seconds_bucket[2m])) by (le))"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 7 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100)"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 12, "w": 12, "h": 7 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name!=\"\"}[2m])) by (name)"
    }
   ]
  }
 ]
}